INSERT INTO People
VALUES (1,"WrathHydra","Monarch","Kingdom of Viperia"),
(2,"LustHydra","Consort","Kingdom of Viperia"),
(3,"PrideHydra","Duke","Kingdom of Viperia"),
(4,"SlothHydra","Lord","Kingdom of Viperia"),
(5, "GluttonyHydra","Lord","Kingdom of Viperia"),
(6, "GreedHydra","Lord","Kingdom of Viperia"),
(7, "DeathVipere","Sovereign","Vipere"),
(8, "ElementalVipere","Command","Vipere"),
(9, "NovaVipere","Command","Vipere"),
(10, "RadiumVipere","Vipere","Vipere"),
(11, "XenonVipere","Vipere","Vipere"),
(12, "NoktusVipere","Vipere","Vipere"),
(13,"AuroraVipere","Vipere","Vipere"),
(14,"AresVipere","Vipere","Vipere"),
(15,"RadonVipere","Vipere","Vipere"),
(16,"SithisVipere","Vipere","Vipere"),
(17,"ApolloVipere","Vipere","Vipere"),
(18,"HydraVipere","Vipere","Vipere"),
(19,"TimeVipere","Vipere","Vipere"),
(20,"VivdVipere","Vipere","Vipere"),
(21,"LetalisVipere","Vipere","Vipere"),
(22, "SpaceVipere","Vipere","Vipere"),
(23,"FluorineVipere","Vipere","Vipere"),
(24,"VanadiumVipere","Vipere","Vipere"),
(25,"IridiumVipere","Vipere","Vipere"),
(26,"ArsenicVipere","Vipere","Vipere"),
(27,"NeonVipere","Vipere","Vipere")