INSERT INTO Quotes (QuoteID, QuoteText, QuoteAuthor)
VALUES (1, "Silence is the language of inevitability; listen well, for the universe whispers its secrets only to those who do not speak.","DeathVipere"),
(2,"The stars themselves tremble when I move, yet none shall ever know my intent.","DeathVipere"),
(3,"A single strike can alter the course of worlds. Do not mistake hesitation for mercy.","DeathVipere"),
(4,"Time bends around the will of the unseen. I am the shadow that guides it.","DeathVipere"),
(5,"Those who seek truth will find only questions. Those who obey… will find survival.","DeathVipere"),
(6,"Every fragment of reality bears my mark, even if it knows it not.","DeathVipere"),
(7,"To speak is to betray the cosmos; I choose silence, and in it, dominion.","DeathVipere"),
(8,"I am the flame that consumes ambition and the shadow that judges greed. All bow, or are broken.","WrathHydra"),
(9,"Viperia exists because I will it; the universe bends to the fury of order.","WrathHydra"),
(10,"Do not mistake wrath for impulse—-it is precision, eternal and unyielding.","WrathHydra"),
(11,"Emotions are tools, and I am the master artisan. Pride, lust, and envy... all tremble at my touch.","WrathHydra"),
(12,"Legions rise and fall, but the Kingdom endures, for I endure beyond them all.","WrathHydra"),
(13,"Let the stars witness the folly of those who challenge my dominion—they shall vanish without a trace.","WrathHydra"),
(14,"The sins of the universe are my currency, and I spend them to forge eternity.","WrathHydra");